export const experiences = [
  {
    name: "anger",
    color: "red",
    intensity: [
      { name: "annoyance" },
      { name: "frustration" },
      { name: "exasperation" },
      { name: "argumentativeness" },
      { name: "bitterness" },
      { name: "vengefulness" },
      { name: "fury" },
    ],
    reactions: [
      { name: "dispute" },
      { name: "be passive-aggressive" },
      { name: "insult" },
      { name: "quarrel" },
      { name: "scream/yell" },
      { name: "simmer/brood" },
      { name: "suppress" },
      { name: "use physical force" },
      { name: "undermine" },
    ],
  },
  {
    name: "fear",
    color: "purple",
    intensity: [
      { name: "trepidation" },
      { name: "nervousness" },
      { name: "anxiety" },
      { name: "dread" },
      { name: "desperation" },
      { name: "panic" },
      { name: "horror" },
      { name: "terror" },
    ],
    reactions: [
      { name: "avoid" },
      { name: "freeze" },
      { name: "hesitate" },
      { name: "ruminate" },
      { name: "scream/yell" },
      { name: "withdraw" },
      { name: "worry" },
    ],
  },
  {
    name: "enjoyment",
    color: "#FCCE65",
    intensity: [
      { name: "sensory pleasure" },
      { name: "rejoicing" },
      { name: "compassion/joy" },
      { name: "amusement" },
      { name: "schadenfreude" },
      { name: "peace" },
      { name: "pride" },
      { name: "fiero" },
      { name: "naches" },
      { name: "wonder" },
      { name: "excitement" },
      { name: "extasy" },
    ],
    reactions: [
      { name: "exclaim" },
      { name: "engage/connect" },
      { name: "gloat" },
      { name: "indulge" },
      { name: "maintain" },
      { name: "savor" },
      { name: "seek more" },
    ],
  },
  {
    name: "disgust",
    color: "green",
    intensity: [
      { name: "dislike" },
      { name: "aversion" },
      { name: "distaste" },
      { name: "repugnance" },
      { name: "revulsion" },
      { name: "abhorrence" },
      { name: "loathing" },
    ],
    reactions: [
      { name: "avoid" },
      { name: "dehumanize" },
      { name: "vomit" },
      { name: "withdraw" },
    ],
  },
  {
    name: "sadness",
    color: "blue",
    intensity: [
      { name: "disappointment" },
      { name: "discouragement" },
      { name: "distraughtness" },
      { name: "helplessness" },
      { name: "hopelessness" },
      { name: "misery" },
      { name: "despair" },
      { name: "grief" },
      { name: "sorrow" },
      { name: "anguish" },
    ],
    reactions: [
      { name: "feel ashamed" },
      { name: "mourn" },
      { name: "protest" },
      { name: "ruminate" },
      { name: "seek comfort" },
      { name: "withdraw" },
    ],
  },
];
